# Generated by Django 2.1 on 2018-09-07 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='amice',
            unique_together={('first_name', 'last_name', 'lichting')},
        ),
    ]
