# Generated by Django 2.1 on 2018-09-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180907_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amice',
            options={'verbose_name_plural': 'Amici'},
        ),
        migrations.AlterField(
            model_name='amice',
            name='lichting',
            field=models.IntegerField(),
        ),
    ]
